// Demo products — replace with real API later
export const PRODUCTS = [
  {
    id: "strike-elite-runner",
    name: "Strike Elite Runner",
    price: 149.99,
    sport: "Running",
    category: "men",
    colors: ["Black", "Grey"],
    sizes: [40, 41, 42, 43, 44, 45],
    rating: 4.8,
    badges: ["New", "Cushion"],
    img: "https://picsum.photos/seed/strike1/1200/900",
    hoverImg: "https://picsum.photos/seed/strike1b/1200/900",
    description: "Responsive cushioning with stable chassis for daily kilometers.",
  },
  {
    id: "strike-iron-trainer",
    name: "Strike Iron Trainer",
    price: 119.99,
    sport: "Training",
    category: "men",
    colors: ["Black", "White"],
    sizes: [40, 41, 42, 43, 44, 45, 46],
    rating: 4.6,
    badges: ["Stability", "New"],
    img: "https://picsum.photos/seed/strike2/1200/900",
    hoverImg: "https://picsum.photos/seed/strike2b/1200/900",
    description: "Flat, grippy base for the gym, HIIT, and functional training.",
  },
  {
    id: "strike-574-classic",
    name: "Strike 574 Classic",
    price: 89.99,
    sport: "Lifestyle",
    category: "men",
    colors: ["Grey", "White"],
    sizes: [40, 41, 42, 43, 44, 45],
    rating: 4.7,
    badges: ["Classic"],
    img: "https://picsum.photos/seed/strike3/1200/900",
    hoverImg: "https://picsum.photos/seed/strike3b/1200/900",
    description: "Heritage silhouette with everyday comfort and durability.",
  },
  {
    id: "strike-court-pro-550",
    name: "Strike Court Pro 550",
    price: 129.99,
    sport: "Basketball",
    category: "men",
    colors: ["White", "Black"],
    sizes: [40, 41, 42, 43, 44, 45],
    rating: 4.5,
    badges: ["Court", "Sale"],
    img: "https://picsum.photos/seed/strike4/1200/900",
    hoverImg: "https://picsum.photos/seed/strike4b/1200/900",
    description: "Retro court look with modern cushioning for all-day wear.",
  },
  {
    id: "strike-velocity-kids",
    name: "Strike Velocity Kids",
    price: 59.99,
    sport: "Kids",
    category: "kids",
    colors: ["Black", "Pink"],
    sizes: [28, 29, 30, 31, 32, 33, 34, 35],
    rating: 4.4,
    badges: ["Kids", "Sale"],
    img: "https://picsum.photos/seed/strike5/1200/900",
    hoverImg: "https://picsum.photos/seed/strike5b/1200/900",
    description: "Soft cushioning and tough outsole from playground to PE.",
  },
];
